spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipes_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "Venky@2135"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never

app:
  data:
    file: classpath:data/US_recipes.json
  loader:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn
